export const names = [
  'Jon Snow',
  'Daenerys Targaryen',
  'Arya Stark',
  'Brandon Stark',
  'Eddard Stark',
  'Robb Stark',
  'Rickon Stark',
  'Sansa Stark',
  'Catelyn Tully',
  'Cersei Lannister',
  'Jaime Lannister',
  'Tyrion Lannister',
  'Tywin Lannister',
  'Petyr Baelish',
  'Samwell Tarly',
  'Jorah Mormont',
  'Theon Greyjoy',
  'Khal Drogo',
  'Margaery Tyrell',
  'Loras Tyrell',
  'Gregor Clegane',
  'Sandor Clegane',
  'Davos Seaworth',
  'Ramsay Bolton',
  'Daario Naharis',
  'Joffrey Baratheon',
  'Renly Baratheon',
  'Robert Baratheon',
  'Stannis Baratheon',
  'Podrick Payne',

  'Peter Benjamin Parker',
  'Mary Jane Watson',
  'Miles Morales',
  'Thor Odinson',
  'Steven Rogers',
  'Anthony Edward Stark',
  'Peter Jason Quill',
  'Bruce Banner',

  'Bruce Wayne',
  'Clark Kent',
  'Lois Lane',
  'Diana Prince',
  'Arthur Curry',
  'Bartholomew Henry Allen',

  'Anakin Skywalker',
  'Luke Skywalker',
  'Leia Skywalker',
  'Han Solo',
  'Lando Calrissian',
  'Obi-Wan Kenobi',
  'Qui-Gon Jinn',
  'Padmé Amidala',
  'Mace Windu',
  'Wilhuff Tarkin',
  'Jango Fett',
  'Boba Fett',
  'Enfys Nest',
  'Kylo Ren',
  'Poe Dameron',
  'Jyn Erso',
  'Chirrut Îmwe',
];
